austintgriffith/burner-wallet

package.json
src/App.js
src/AppOld.js
src/components/BalanceDisplay.jsx
src/components/BridgeButton.jsx
src/components/BurnDisplay.jsx
src/components/ClaimId.jsx
src/components/Claimed.jsx
src/components/CopyDisplay.jsx
src/components/HostName.jsx
src/components/LoaderBar.jsx
src/components/Main.jsx
src/components/QRCodeScanner.js
src/components/Scanner.jsx
src/components/SendLink.jsx
src/components/SendTo.jsx
src/components/SendWithLink.jsx
src/components/SentToDisplay.jsx
src/index.js

Added Confirm Dialog. This code also has cleaned up React as per Issue #4.

Fix For Issue #2 Confirm Burn

---

README.md
package.json
run.sh

This was preventing the qr-code-reader module from working across both mobile and desktop. I also tested on FireFox.

Setting HTTPS env variable to true 

---

package.json
src/App.js
src/components/Main.jsx
src/components/ReceiveLink.jsx
src/components/RequestReceive.jsx
src/components/SendTo.jsx

I had a shot at adding the Adding: Request Funds functionality #19 and I think I've got something pretty nice working.
1. User clicks the new Request A Payment button on the main page.
2. Can enter an amount and a message then click Request
3. This creates a QR/Link similar to the Send With Link function. The link looks like: http://localhost:3000/receive_request/amount;address;message
4. The link can be copied and sent. When someone else gets it the app will parse the data and load the SendTo component with the details filled in.

Adding: Request Funds functionality #19

---

contracts/Links/Links.sol
src/App.js

This pull request will fix the smart contract bugs. 
On the Front-end there is more work to do to optimize the wallets.
The parameter nonce for the hashOfDestination could be better to get them from the URL.

Links Smart Contract Fixes

---

contracts/Links/Links.sol
src/App.js
xdairelay.js

#47 First step towards send with link enhancements. SC changes.
Validate claimHash in the smart contract.
No breaking changes on this PR. Keeps same functionality but allows future send with links enhancement.

First update for send with link enhancement.

---

src/App.js
src/components/Bottom.js
src/components/RequestFunds.js
src/i18n/index.js
src/i18n/locales/en.json

@dbe @austintgriffith please take look

Additional fixes on internationalization.

---

src/i18n/locales/fr.json

Hey folks!
Just dropping in french translations that I finished up. French isn't my native language, although I've taken it up to pre-University standards, so I might not have all the slang perfect. I'll drop a link on Twitter too and see if a native speaker can just look it over once. 
Other than that, everything should be good to go.
If I find time over the next few days, I'll drop in a Hindi translation.
Cheers!
Anish

Adding french UI translations.

---

src/i18n/locales/ca.json

Bounties and/or attribution welcome: 0x2d77946b1e5478db5ff817c70544f733428a4937

Catalan translation

---

src/i18n/locales/de.json

Hello there,
just finished the German translation and added it as a locale. If someone sees room for improvement in my translation I'm always open and happy for feedback!
Also happy to update it once there are changes necessary in the future.
Keep up the good work!

Add german locale

---

src/components/Exchange.js
src/services/wyre.js

- Add onClose event handler to Wyre service.
- Show spinner when Wyre Widget is open.

Show Spinner on Wyre Button with Open Widget

---

src/i18n/index.js

Should fix: https://github.com/austintgriffith/burner-wallet/issues/128
My bad.

Fix fallback language

---

src/App.js
src/Container.js
src/components/History.js
src/components/Loader.js
src/components/Receipt.js
src/components/Receive.js
src/components/RecentTransactions.js
src/components/RequestFunds.js
src/components/SendToAddress.js
src/components/SendWithLink.js
src/config.js
src/contexts/TransactionStore.js
src/index.js

Moves all code that deals with storing recent transactions into the TransactionStore context component, and provides the data to any component that consumes it.
Dependent on #143, which should be merged first.

Refactor transaction history into TransactionStore

---

src/App.js
src/components/RequestFunds.js
src/components/SendToAddress.js
src/components/SendWithLink.js
src/config.js

First of hopefully many PRs to reactor and organize the wallet code.
This just moves many of the variables that were defined at the top of App.js into the new file, config.js

Move configuration variables to config.js

---

package.json
src/App.js
src/Container.js
src/components/Header.js
src/components/Receive.js
src/components/RecentTransactions.js
src/components/RequestFunds.js
src/components/SendBadge.js
src/components/SendToAddress.js

Instead of saving the current view as the `view` state variable in App.js, the react-router package has been added and will handle the view state.

Use React Router for routing

---

src/App.js
src/components/Admin.js
src/components/Balance.js
src/components/BurnWallet.js
src/components/Exchange.js
src/components/History.js
src/components/Loader.js
src/components/MainCard.js
src/components/Receipt.js
src/components/Receive.js
src/components/RecentTransactions.js
src/components/RequestFunds.js
src/components/SendByScan.js
src/components/SendToAddress.js
src/components/SendWithLink.js
src/components/Vendor.js
src/components/Vendors.js
src/components/WithdrawFromPrivate.js
src/lib.js

Continuing the work from #143, this PR prevents prop drilling by importing values directly from config.js, and functions directly from lib.js

Refactor code into lib & config

---

src/App.js
src/components/Header.js

Fix the header to handle react router paths

Fix and clean up header

---

src/App.js

Fixes #146
Edit: Currently xdai.io shows $0.00 even though I have eth. Might be related.

Use Uniswap analytics API instead of Coinmarketcap

---

contracts.clevis
contracts/ScavengerHunt/ScavengerHunt.sol
contracts/ScavengerHunt/arguments.js
contracts/ScavengerHunt/dependencies.js
src/App.js
src/components/MainCard.js
src/components/ScavengerHunt.js
src/contracts/contracts.js

This is still Work in Progress. Just submitting for the hackathon.
ScavengerHunt contract is done for the most part, just still need to hook up the UI to the contract.
Need owner view and user view.
Hard coded to 5 questions with contract deployment, Answers ["zero", "one", "two", "three", "four"]
Basic flow:
Deploy contract with answers and gameEndTime and revealEndTime
On deployment game starts:
CommitPhase: User can commitAnswer for any question.
After gameEndTime, Owner needs to call endGame with his answer and salt
RevealPhase: Then users can revealAnswers
After revealEndTime: Anyone can call findWinner, which will find winner and send them whatever balance the contract has.

Module scavenger hunt

---

package.json
public/index.html
src/App.js
src/components/Advanced.js
src/components/Bottom.js
src/components/Helena.js
src/components/Loader.js
src/components/MainCard.js
src/components/MoreButtons.js
src/components/NavCard.js
src/components/Receipt.js
src/components/Receive.js
src/components/RecentTransactions.js
src/components/RequestFunds.js
src/components/SendByScan.js
src/components/SendToAddress.js
src/components/WithdrawFromPrivate.js
src/index.scss
src/theme.js

Modified most view layouts to use Flexbox for alignment and spacing. 
Swapped existing buttons for Rimble Button component. 
Fixed layout issues with initial loader and background image.
Updated some instances of Loaders to have a Card background to improve visibility.
Wrapped all Rimble components in ThemeProvider for easier color changes.

Updated UI with Rimble components

---

src/components/SendToAddress.js

Switched the rimble Input component back to HTML5 input. Styled to match other Rimble inputs.

Reverted back to HTML5 input

---

src/components/SendBadge.js

Used same layout as the SentToAddress view.

Swapped in Rimble UI components in SendBadge view.

---

src/App.scss
src/components/Header.js

Added white background and padding the Header blockie, wallet address, and connected network for more visibility.

Added Card background to Header for improved readability.

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE.md

added funding and issue template

---

src/App.js

Fixes #187 
PR is basically a copy of #158 (was rolled back).

Add block to request_funds route

---

src/App.js
src/components/Balance.js
src/core.js

PR #229 integrated burner-core for reading token balances, however this did not support local test tokens.
This PR checks if the local injected chain has the ID 5777 (Ganache), and if so, uses the deployed token as the "xDai" asset.

Display Test Ganache token balances with burner-core

---

src/App.js
src/components/Exchange.js

In an effort to transition the codebase to use of burner-core, this replaces the construction of Web3 objects with the `core.getWeb3` function.

Use burner-core to get chain-specific web3s
